#!/bin/bash 
#PBS -o /data_group/kongqingpeng/wanghaotian/cmds/pbs_out/MuTect2_275.o
#PBS -e /data_group/kongqingpeng/wanghaotian/cmds/pbs_out/MuTect2_275.e 
#PBS -N Mutect2_275
#PBS -q workq  
#PBS -l mem=150gb,walltime=25:00:00 
#PBS -l nodes=1:ppn=20 

sample='sample275'

#The scripts uses PoN file of 1000G as normal samples

for i in `seq -f '%04g' 0 19`
do
    gatk Mutect2 -R /data_group/kongqingpeng/wanghaotian/BasicResource/Ref/Homo_sapiens_assembly38_gatk.fasta -I /data_group/kongqingpeng/wanghaotian/Data/0_bwa_bam/${sample}.dedup.BQSR.sorted.bam -tumor ${sample} -L /data_group/kongqingpeng/wanghaotian/BasicResource/GATK_bundle/hg38_scatter_interval_files/$i-scattered.interval_list --germline-resource /data_group/kongqingpeng/wanghaotian/BasicResource/GATK_bundle/af-only-gnomad.hg38.vcf.gz --af-of-alleles-not-in-resource 0.00003125 --panel-of-normals /data_group/kongqingpeng/wanghaotian/BasicResource/GATK_bundle/1000g_pon.hg38.vcf.gz -O /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.$i.vcf.gz &
done
wait

gatk GatherVcfs -O /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0000.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0001.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0002.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0003.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0004.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0005.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0006.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0007.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0008.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0009.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0010.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0011.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0012.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0013.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0014.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0015.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0016.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0017.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0018.vcf.gz \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.0019.vcf.gz \
    
gatk SortVcf -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.vcf.gz \
    -O /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.sorted.vcf.gz
    
rm /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}*00*



#GetPileupSummaries
gatk GetPileupSummaries \
    -L /data_group/kongqingpeng/wanghaotian/BasicResource/GATK_bundle/chromosome_intervals.intervals\
    -I /data_group/kongqingpeng/wanghaotian/Data/0_bwa_bam/${sample}.dedup.BQSR.sorted.bam \
    -V /data_group/kongqingpeng/wanghaotian/BasicResource/GATK_bundle/af-only-gnomad.hg38.SNP_biallelic.vcf.gz \
    -O /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.pileups.table
    
#
gatk CalculateContamination \
    -I /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.pileups.table \
    -O /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_con.table 
    
gatk FilterMutectCalls \
    -R /data_group/kongqingpeng/wanghaotian/BasicResource/Ref/Homo_sapiens_assembly38_gatk.fasta \
    -V /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.sorted.vcf.gz \
    -contamination-table /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_con.table \
    -O /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.filtered.vcf.gz
    
bcftools filter -Oz -o /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.filtered.PASS.vcf.gz \
    -i 'FILTER=="PASS" & GERMQ>=30 & INFO/DP>=20' /data_group/kongqingpeng/wanghaotian/Data/1_vcfs/${sample}_somatic.filtered.vcf.gz
